# Generated by Django 2.0.13 on 2019-03-14 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to', to=settings.AUTH_USER_MODEL),
        ),
    ]
