# Generated by Django 2.0.13 on 2019-03-14 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0007_notification_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='creator',
        ),
        migrations.AddField(
            model_name='notification',
            name='fromwhom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fromwhom', to=settings.AUTH_USER_MODEL),
        ),
    ]
