# Generated by Django 2.0.13 on 2019-03-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20190315_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='comments',
            new_name='commentss',
        ),
    ]
