# Generated by Django 2.0.13 on 2019-03-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_tags'),
        ('notifications', '0009_auto_20190315_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='image',
        ),
        migrations.AddField(
            model_name='notification',
            name='imagess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imagess', to='images.Image'),
        ),
    ]
