# Generated by Django 2.0.13 on 2019-03-14 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0004_image_tags'),
        ('notifications', '0010_auto_20190315_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='commentss',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='fromwhom',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='imagess',
        ),
        migrations.AddField(
            model_name='notification',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image', to='images.Image'),
        ),
    ]
