# Generated by Django 2.0.13 on 2019-03-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20190315_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
